// Auto-generated sample data - Do not modify manually
import { ILodging, ILodgingResponse, ICreateLodgingParams, IUpdateLodgingParams } from "./lodging.interface";

export const lodgingSample: ILodging = {
  "id": "",
  "uuid": "",
  "trip_id": "",
  "trip_uuid": "",
  "is_client_traveler": false,
  "relative_url": "",
  "display_name": "",
  "is_display_name_auto_generated": "",
  "last_modified": "",
  "booking_rate": "",
  "booking_site_conf_num": "",
  "booking_site_name": "",
  "booking_site_phone": "",
  "booking_site_url": "",
  "supplier_conf_num": "",
  "supplier_contact": "",
  "supplier_email_address": "",
  "supplier_name": "",
  "supplier_phone": "",
  "supplier_url": "",
  "is_purchased": false,
  "notes": "",
  "restrictions": "",
  "total_cost": "",
  "is_tripit_booking": false,
  "is_concur_booked": "",
  "StartDateTime": {
    "date": "",
    "time": "",
    "timezone": "",
    "utc_offset": "",
    "is_timezone_manual": ""
  },
  "EndDateTime": {
    "date": "",
    "time": "",
    "timezone": "",
    "utc_offset": "",
    "is_timezone_manual": ""
  },
  "EstimatedStartDateTime": {
    "date": "",
    "time": "",
    "timezone": "",
    "utc_offset": "",
    "is_timezone_manual": ""
  },
  "Address": {
    "address": "",
    "city": "",
    "state": "",
    "zip": "",
    "country": "",
    "latitude": "",
    "longitude": "",
    "risk_level": ""
  },
  "number_guests": "",
  "number_rooms": "",
  "room_type": "",
  "Image": []
};

export const lodgingSampleResponse: ILodgingResponse = {
  "timestamp": "",
  "num_bytes": "",
  "Warning": {
    "description": "",
    "entity_type": "",
    "timestamp": ""
  },
  "LodgingObject": {
    "id": "",
    "uuid": "",
    "trip_id": "",
    "trip_uuid": "",
    "is_client_traveler": false,
    "relative_url": "",
    "display_name": "",
    "is_display_name_auto_generated": "",
    "last_modified": "",
    "booking_rate": "",
    "booking_site_conf_num": "",
    "booking_site_name": "",
    "booking_site_phone": "",
    "booking_site_url": "",
    "supplier_conf_num": "",
    "supplier_contact": "",
    "supplier_email_address": "",
    "supplier_name": "",
    "supplier_phone": "",
    "supplier_url": "",
    "is_purchased": false,
    "notes": "",
    "restrictions": "",
    "total_cost": "",
    "is_tripit_booking": false,
    "is_concur_booked": "",
    "StartDateTime": {
      "date": "",
      "time": "",
      "timezone": "",
      "utc_offset": "",
      "is_timezone_manual": ""
    },
    "EndDateTime": {
      "date": "",
      "time": "",
      "timezone": "",
      "utc_offset": "",
      "is_timezone_manual": ""
    },
    "EstimatedStartDateTime": {
      "date": "",
      "time": "",
      "timezone": "",
      "utc_offset": "",
      "is_timezone_manual": ""
    },
    "Address": {
      "address": "",
      "city": "",
      "state": "",
      "zip": "",
      "country": "",
      "latitude": "",
      "longitude": "",
      "risk_level": ""
    },
    "number_guests": "",
    "number_rooms": "",
    "room_type": "",
    "Image": []
  }
};

export const createCreateLodgingParams: ICreateLodgingParams = {
  "bookingRate": "",
  "bookingSiteConfNum": "",
  "bookingSiteName": "",
  "bookingSitePhone": "",
  "bookingSiteUrl": "",
  "recordLocator": "",
  "supplierConfNum": "",
  "supplierContact": "",
  "supplierEmailAddress": "",
  "supplierPhone": "",
  "supplierUrl": "",
  "notes": "",
  "restrictions": "",
  "totalCost": "",
  "bookingDate": "",
  "isPurchased": false,
  "tripId": "",
  "hotelName": "",
  "checkInDate": "",
  "checkOutDate": "",
  "checkInTime": "",
  "checkOutTime": "",
  "timezone": "",
  "street": "",
  "city": "",
  "state": "",
  "zip": "",
  "country": "",
  "numberGuests": 0,
  "numberRooms": 0,
  "roomType": ""
};

export const updateUpdateLodgingParams: IUpdateLodgingParams = {
  "uuid": "",
  "tripId": "",
  "isPurchased": false,
  "Image": [],
  "bookingRate": "",
  "bookingSiteConfNum": "",
  "bookingSiteName": "",
  "bookingSitePhone": "",
  "bookingSiteUrl": "",
  "recordLocator": "",
  "supplierConfNum": "",
  "supplierContact": "",
  "supplierEmailAddress": "",
  "supplierPhone": "",
  "supplierUrl": "",
  "notes": "",
  "restrictions": "",
  "totalCost": "",
  "bookingDate": "",
  "hotelName": "",
  "checkInDate": "",
  "checkOutDate": "",
  "checkInTime": "",
  "checkOutTime": "",
  "timezone": "",
  "street": "",
  "city": "",
  "state": "",
  "zip": "",
  "country": "",
  "numberGuests": 0,
  "numberRooms": 0,
  "roomType": ""
};

